### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by SamuelScheit** [discord-userdoccers/discord-userdoccers#155]
A user can setup push notifications for apple and google services by making the following request:
```http
POST https://discord.com/api/v9/users/@me/devices
```
with the following JSON request body:
```json
{
	"provider": "apns",
	"token": "..."
}
```
where `provider` can be `gcm` (Google Cloud Messaging), `apns` (Apple Push Notification System) or `apns_voip` (Apple Push Notification System for Voice over IP)
and the corresponding `token` of the provider platform.

**Comment by dolfies** [comment]
Feel free to PR this! The project is in an early state and there aren't many qualified contributors.

**Comment by dolfies** [comment]
Setup was documented in a recent commit; the full notification system remains undocumented though.

**Comment by SamuelScheit** [comment]
I see that the push notification has changed and can confirm that the updated docs are correct as of now.
What else is missing about the notification system?
