### ISSUE TITLE
Decrypting `aead_aes256_gcm_rtpsize`

### ISSUE THREAD

**Issue by techchrism** [discord-userdoccers/discord-userdoccers#180]
Currently, my native discord client defaults to using the `aead_aes256_gcm_rtpsize` encryption method for voice webrtc and I'm struggling to decrypt the packets.

The packets being received have a header of `0x90` `0x78` instead of `0x80` `0x78` which is the first notable discrepancy with the docs.
Using the packet stripped of the first 12 bytes (header) and last 4 bytes (nonce) and attempting to decrypt with the 4 nonce bytes and the key doesn't seem to work though perhaps I'm doing it wrong.

Have you managed to decrypt `aead_aes256_gcm_rtpsize`-encrypted packets?

Thank you.

**Comment by arHSM** [comment]
Have you taken a look at <https://datatracker.ietf.org/doc/html/rfc7714>?

**Comment by techchrism** [comment]
I have looked at it and determined the `0x90` byte indicates an extension and for all the messages I'm inspecting, the extension length is always `0x01` indicating 4 bytes. I'm not sure what these 4 bytes indicate. The profile-defined bytes seem to always be `0xBE 0xDE`

Could you elaborate on the decryption process? Thank you.

**Comment by arHSM** [comment]
Okay so here's what I've compiled, yes `0x90` indeed indicates the use of extensions by [RFC 3550](https://www.rfcreader.com/#rfc3550), according to which you'll have to parse the extensions header [defined here](https://www.rfcreader.com/#rfc3550_line815), you're receiving a ["one byte header" (`0xBE 0xDE`) defined in RFC 5285](https://www.rfcreader.com/#rfc5285_line186)
After parsing the header and the extension header you'll have to decode your data via aead_aes256_gcm decryption, the key would be what you passed in [session description](https://discord-userdoccers.vercel.app/topics/voice-connections#session-description-structure)
although I'm not sure about 2 things, 1. what the required AAD would be to decrypt, 2. what `rtpsize` is supposed to signify

**Comment by techchrism** [comment]
Yeah, I'm definitely unsure of the AAD. Because the messages were short enough (<200 bytes) I whipped up a quick script to try decrypting every possible consecutive sequence of bytes in the packet while attempting to use the first/last `128, 120, 112, 104, 96, 64, 32` bits of that sequence as the auth tag while *also* trying every 4-16 byte sequence in every position in the packet as the nonce.

It took a while to run but didn't produce any results unfortunately.

**Comment by arHSM** [comment]
I would like to give it a try if you could provide an example rtp packet with the encryption key

**Comment by techchrism** [comment]
Sure, here's the key and a few sequential base64'd incoming packets (delimited by newlines):
```
{"encryptionSettings":{"mode":"aead_aes256_gcm_rtpsize","secretKey":[132,244,238,26,227,36,103,105,93,232,123,62,36,129,53,217,205,168,182,150,10,231,173,237,7,53,120,237,158,221,138,114]}}
```

```
kHiZi+XI4a8ABsFcvt4AAZ3DA2+eQKqlc9Vq+wspWqmRCc+JJXI96IzRjA9JmMvtjDdopqMg+rUdY90F2ex8a9Ad7DLMfy+qj2PP3fWjL3R9HQ3NI5RQLmxy2ZUQ/MAb1Zee7SyAEcS0OSW7kL7jyPjCaotqNm0W9U8Ku+6Rcwj6w4fY7/YV6yyRzhMjHf6D1TDpul57dyQ/s/0z1FWIX8KqTL8YAcIlQDg/w6f9LkRsLp+z/RytPXoksmfYA27M5z6h6HNetoedXws4+XPiq5Dv9KYeqI2k5BEAAAA=
kHiZjOXI5W8ABsFcvt4AAaDrPyuWoZfQte1Ngyu4IxqIWgVrVVBB4cv4wCKDSeXkSmH/uT9WA+gIV9NOuXcbdtuM29/SLE2Ol5JPQIRLCTKrXHCD1sKlPP4G0tlOQIs9Vt8Lb+eCA2McfhxJEX5hqbkLBehekYOGK8753OCJbCx2YuOefe0STHY3zvba1aDXpxxvQYn0KDZbbZsMwE4hAwPqy4NHTiS1XrkbjmFbR85EZf+/HawL76ezCDE5iD7MhLrvEgAAAA==
kHiZjeXI6S8ABsFcvt4AAbQL06fYe+EKGLdFbMhoAm02ADp8wnAXnGf1Q/2XRlaPWlv8E0Zm66W7/FEq2B3zRyyuWd9rOVWsNqJ2n467aRIHCAUOrzdFIqBqfidz1UHa0se000aZA5ygqm3lVQZqkQ1NAVn7a17wHr7MJVBHeUxLYzTmIV/Y2DXQmPjl8LuQIZ2PVdZMzoiS0Pm32XOaz5OcW47nW5sZr+XX0UI0TlIPKC0YZNNm/zF80BcoAxQdr3fYyC/B6xXh/vwTAAAA
kHiZjuXI7O8ABsFcvt4AAd/H4N7tqM0iSNOLx8MyL8fbeOH0lvWoUImDXQsET9Kgx6v4YUWkxZBuDvLE4VQSMr8utnk4soiqa33zpDL6ntD0nmpqGok2rsK+Or45khpvJJ2ixGWsIu+Sz4I9hBiS2fLuaeepp13UAP2ydf09sT0Lj9/F5nzblq+v6krNTsUGVVmkX14KhqEGTDffLF5CKfH7gqLGuIMQgbcawgW2SoOdgieC5PSGZoaw30b68Qvg5GTyOZ3oDx7z2OIUAAAA
kHiZj+XI8K8ABsFcvt4AAcs0q2FUeRyGVekJzJB2ZTLxPkv75ExUTfq1oLdOUV/lfugYo94jMyVL6h5z2JcYq4D4Y+wobFLmQ4HQNv5hePVExL5K0u9AufAuNFcGOj1PKsHXKEOR4v76g9urw6KFAVrA+1O0jfY9Of2OLNGgW3Xgulc+haK6+Gq8UDPTEzUvca672eMa7m5yZdZPDIBBLSPFL7zZRXb1dRSMT+xLDzvvVCnSW6WelWR/KWTzvV/eSLIVAAAA
kHiZkOXI9G8ABsFcvt4AAYAxEdRQC/UPLk12Jrzro0PZMi4wAdOa8nQVH9kTc2l+xng7kXyaaOGFRAG/XhaaIEWTifBkJv45KhkKjuwBhUBOCRzV7+qVoII6m7rPJuTy01rlCSlNA9i7S7HAu36JtIkRCHcS401kvv/GsYZZdvOqvAFWwBQEh9KrfNSJn/y41NTbGfikW0RfR1auSIQZ8t+/jW9z11dLoFKCTyjBcKwL8be417Z3xZwp+Nkor20uFgAAAA==
kHiZkeXI+C8ABsFcvt4AAaBNd6AleCwMya7+cJtFi59sOWsCEkH5wEOvTNtJtKyWRoQZ76D6oawZuMdSeS1wVF5d93adTFYWeZKC4iPm2ruINOYVIjP0etnnb6KtSq9EpCwvlDP7bUxLAZ5bR8fb8iybVBBndUAx4icvw9h56L+H+/snV/uYo/tID98x52HhwVDblCy2I7UVP5uMzqmFmhcHOp25/1BVfN5Fx/z/HljAMlivJtWiOzvLDCUXAAAA
kHiZkuXI++8ABsFcvt4AAYVYToLCTwp+LdUYTtTB5VhkIw/4b4/bT9pB6pErPZLOszHWDFVUm+R3vfHU5aFxruV1Gm0Ku1q9zUD6lpw1xf1i2OLZcd/eU9w8hUr4OEJbDPvfFwDcMzJJNIRrzwDgCbTPPWCyaOl2RbpwYK6zVp7ed4wqftiOn9LtDSYLF5+TBQXfhcB/Bs1bwZ8UHSfUaF+0tBVWcaiH9HB0zNUbsfeNz9DYvn8G+RULl7bRmeYYAAAA
kHiZk+XI/68ABsFcvt4AAVMDLlfIznERJsgJ1TSxIjIauI8+ws3A9dJay5tiAE4bkbZT/5VJ8t74DEDL30FCcdJOVNqCs2QIFzhKLfeXqVtZlIHe4Ts3p5BjCl/Ar2KUTyTMUoGsCiOANK2foeAfF4JOHuobsiaWd6ixh73vurHeaCT+Ssb9/q7926Cs+OcbkR4CLjAzMQP+ZTFqBX/MRH2jwfQaLU5bAQZ3soP5yUJO4wu9hYZ/GTbG7RkAAAA=
```

**Comment by arHSM** [comment]
```ts
const header = parseRTPHeader(payload);

const offset = header.headerSize;
const aad = payload.subarray(0, offset);
const authTag = payload.subarray(payload.length - 16);
const data = payload.subarray(offset, payload.length - 16);

function parseRTPHeader(packet: Buffer) {
    const version = packet[0] >> 6;
    const padding = (packet[0] & 0b00100000) >> 5;
    const extension = (packet[0] & 0b00010000) >> 4;
    const csrcCount = packet[0] & 0b00001111;

    const marker = packet[1] >> 7;
    const payloadType = packet[1] & 0b01111111;

    const sequenceNumber = packet.readUInt16BE(2);

    const timestamp = packet.readUInt32BE(4);

    const ssrc = packet.readUInt32BE(8);

    let headerSize = 12;
    const csrc = [];
    const extensions: Record<string, Buffer> = {};

    for (let i = 0; i < csrcCount; i++) {
        csrc.push(packet.readUInt32BE(headerSize));
        headerSize += 4;
    }

    if (extension) {
        if (packet[headerSize] === 0xbe && packet[headerSize + 1] === 0xde) {
            headerSize += 2;

            const length = packet.readUint16BE(headerSize);
            headerSize += 2;

            let n = 0;

            while (n < length) {
                const next = packet[headerSize];
                headerSize++;

                if (next === 0x00) {
                    continue;
                }

                const id = next >> 4;
                const len = next & 0b00001111;

                extensions[id.toString(10)] = packet.subarray(
                    headerSize,
                    headerSize + len
                );

                headerSize += len;

                n++;
            }
        }
    }

    return {
        version,
        padding,
        extension,
        csrcCount,
        marker,
        payloadType,
        sequenceNumber,
        timestamp,
        ssrc,
        csrc,
        extensions,
        headerSize,
    };
}
```

given the rtp payload you can get the AAD, auth tag, and the cipher text I am not sure how the IV is supposed to be formed

**Comment by techchrism** [comment]
The last 4 bytes of the packet are an incremental counter which from what I understand (admittedly very little), wouldn't appear in an auth tag.
I tried shifting the auth tag back 4 bytes and using the last 4 bytes as the nonce but that didn't seem to work, even when the nonce was padded on either side with 8 0x00 bytes.

Here's what the code currently looks like:
```typescript
const header = parseRTPHeader(buffer)

const offset = header.headerSize
const aad = buffer.subarray(0, offset)
const nonce = buffer.subarray(buffer.length - 4)
const authTag = buffer.subarray(buffer.length - 16 - 4, buffer.length - 4)
const data = buffer.subarray(offset, buffer.length - 16 - 4);

const decipher = crypto.createDecipheriv('aes-256-gcm', key, nonce)
decipher.setAuthTag(authTag)
decipher.setAAD(aad)
const decrypted = Buffer.concat([decipher.update(data), decipher.final()])
```

It gives the usual error:
```
Error: Unsupported state or unable to authenticate data
```

**Comment by arHSM** [comment]
As far as I know discord uses libsodium to encrypt packets on their end (as mentioned in the official docs). I took a quick look at libsodium source (and assuming discord is using non `_detached` variant of encoding) the last 16 bytes of the packet are supposed to be the auth tag
As for the nonce/initialisation vector I have been looking into [using a ROC](https://github.com/webrtc-rs/webrtc/blob/master/srtp/src/context/mod.rs#L43-L70)

**Comment by arHSM** [comment]
Someone has reimplemented the [`discord_voice`](https://git.kaydax.xyz/w/algos) module which contains the encryption modes (+ others) which you're looking for. [`aead_aes256_gcm_rtpsize`](https://git.kaydax.xyz/w/algos/src/branch/main/src/module/util/crypt_impl.cc#L134-L147) in question.
