### ISSUE TITLE
Guild and DM sorting endpoints missing!

### ISSUE THREAD

**Issue by ThaBluNate** [discord-userdoccers/discord-userdoccers#244]
Maybe I'm just blind, but I didn't find these on https://discord.sex/
Originally, in the pursuit of making cool shit, I asked on the discord developers discord about this endpoint:
![image](https://github.com/user-attachments/assets/5fbdaeca-87f8-41f2-97a2-2b6a4d3de986)
![image](https://github.com/user-attachments/assets/f488e62e-c6d0-4ce5-8131-5405b7f9d731)

Obviously, it didn't go as intended. then I found ~~discord sex~~ these non-officially documented endpoints!
Well, I couldn't find it. Again, maybe I'm blind. 2:00 AM hit pretty hard- but if I'm not- the mission is hunt and kill.

**Comment by dolfies** [comment]
https://docs.discord.sex/resources/channel#get-private-channels already documented :)
The order isn't something documented because it isn't guaranteed and shouldn't be relied on

**Comment by ThaBluNate** [comment]
I already knew how to do that. the question was about getting the correct order, as listed in the discord client

**Comment by dolfies** [comment]
The order is in user settings, which are not yet documented. You can use the deprecated route `GET /users/@me/settings` or connect to the gateway without the `USER_SETTINGS_PROTO` capability to get the deprecated JSON object, or `GET /users/@me/settings-proto/1` and parse the protobufs using https://github.com/dolfies/discord-protos.

**Comment by ThaBluNate** [comment]
It's unfortunate protobufs aren't documented because i'm not using npm, and i'd rather this remain as close as possible right now

**Comment by dolfies** [comment]
The raw .proto files are provided there as well! Feel free to pr to the repo and edit the workflow to produce packages other than py/js if you want

**Comment by dolfies** [comment]
Also if you're modifying the client, you don't need to do any of this, you can just use the client's inbuilt functions

**Comment by ThaBluNate** [comment]
Nope, making my own

**Comment by dolfies** [comment]
https://protobuf.dev/

Best of luck!

**Comment by ThaBluNate** [comment]
O, I just realized protobuf.js has a browser option!
