### ISSUE TITLE
Endpoint missing: /users/@me/settings

### ISSUE THREAD

**Issue by nexusprime-here** [discord-userdoccers/discord-userdoccers#275]
Missing endpoints:
- `GET` /api/v9/users/@me/settings
- `PATCH` /api/v9/users/@me/settings

The GET returns all user settings possibilities, and using PATCH you can update it.
If someone wants to create the PR to update this, I would appreciate it. I will create it, but it will take a little while.

Why the hell is this called 'discord.sex'? BRUH

**Comment by nexusprime-here** [comment]
lmao

**Comment by aamiaa** [comment]
FWIW that endpoint is deprecated in favor of `/users/@me/settings-proto/:type`, which should probably be documented first (along with a dedicated docs page explaining how settings work).

> Why the hell is this called 'discord.sex'? BRUH

Why not make use of a funny domain 😋
