### ISSUE TITLE
Application create needs a second request

### ISSUE THREAD

**Issue by nexusprime-here** [discord-userdoccers/discord-userdoccers#276]
When you use a `POST` /api/v9/application, in 4 seconds it will be deleted if you don't use a other API. I think is /api/v9/science. I'll check

**Comment by aamiaa** [comment]
That's an antispam measure which is based on many factors. We don't document those here.

**Comment by nexusprime-here** [comment]
> That's an antispam measure which is based on many factors. We don't document those here.

Mm, sorry. You know about this antispam? I'm suffering with this shit
