### ISSUE TITLE
New message flag (again)

### ISSUE THREAD

**Issue by BoryaGames** [discord-userdoccers/discord-userdoccers#285]
Discord has added new message flag, what it does is unknown.

1 << 16 | SENT_BY_SOCIAL_LAYER_INTEGRATION

**Comment by BoryaGames** [comment]
It was added [here](https://github.com/Discord-Datamining/Discord-Datamining/commit/8d6cf579dc7ca513ab66bedebd2c38f98e3e9dc0#commitcomment-147457379) and somehow related to this:
![Image](https://github.com/user-attachments/assets/69ae97a9-f073-4091-b191-589d046af985)

**Comment by dolfies** [comment]
Done
